[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
    "@aave-v3-core/=lib/aave-v3-core/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
